name: Deploy to My Server

on:
  push:
    branches: [ "develop" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Publish App
        run: |
          dotnet publish -c Release -o ./publish
          tar -czvf app.tar.gz ./publish

      - name: Deploy via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "app.tar.gz"
          target: "/home/deploy"

      - name: Run on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy
            tar -xzf app.tar.gz
            sudo systemctl stop myapp.service  # Останавливаем предыдущую версию
            sudo cp -r publish/* /var/www/myapp/
            sudo systemctl start myapp.service
